name: responsive_navigation_bar_example
description: Demonstrates how to use the responsive_navigation_bar package.

publish_to: 'none'

environment:
  sdk: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_navigation_bar:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.2.0  

flutter:
  uses-material-design: true
